# Preedit Mode
PreeditMode="Composing text"
# Shared Input State (NoShare = each program gets its own Rime state)
InputState=NoShare
# Fix embedded preedit cursor at the beginning of the preedit
PreeditCursorPositionAtBeginning=True
# Action when switching input method
SwitchInputMethodBehavior=Clear
# Synchronize
Synchronize=

[Deploy]
0=
